"""Skills — shippable procedural knowledge that sits on top of tools.

Layering (respected strictly): loop at the bottom, tools above it, skills
orchestrating tools. A skill NEVER replaces the tool system — it declares which
tools it expects and provides the procedure that uses them.

Forward-compat Property 2: a skill is LOADED DATA with a stable schema (markdown
+ frontmatter), never hardcoded in Python — so a skill could later be
rewritten/regenerated by editing the file.

The skill-selection strategy is itself under test (SKILL_SELECTION_MODE). Both
selectors return the SAME SkillContext, so the loop consumes them identically and
never branches on selection mode.
"""
from __future__ import annotations

import json
import logging
import os
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional

import yaml

from engine.tools.base import Tool

log = logging.getLogger("argus.skills")

# A skill may embed a ```steps fenced JSON block of structured TOOL/MODEL steps (same shape as a
# routine). When present, the skill runs DETERMINISTICALLY through the routine executor — the
# harness dispatches the tool steps itself and only calls the model for model steps — instead of
# injecting prose for the model to follow. The prose body still serves as documentation/fallback.
_STEPS_RE = re.compile(r"```steps\s*\n(.*?)\n```", re.DOTALL)


def _extract_steps(body: str, name: str) -> list:
    """Pull and shape-validate a skill's optional ```steps block. Returns [] (prose-only skill) if
    absent, not valid JSON, not a list, or not a valid step sequence — a bad block never breaks the
    skill, it just falls back to model-driven prose."""
    m = _STEPS_RE.search(body or "")
    if not m:
        return []
    try:
        data = json.loads(m.group(1))
    except Exception as e:
        log.warning("skill %s: ```steps block is not valid JSON, ignoring it: %s", name, e)
        return []
    if not isinstance(data, list):
        log.warning("skill %s: ```steps must be a JSON array, ignoring it", name)
        return []
    try:
        from engine.routines.store import Routine, validate_routine
        r = Routine(name="skill_steps", steps=data)
        validate_routine(r)          # shape-only (no tool existence check); fills default step ids
        return r.steps
    except Exception as e:
        log.warning("skill %s: invalid ```steps, ignoring them: %s", name, e)
        return []


def reveal_skill_tools(disclosure, skill) -> list[str]:
    """Make a skill's declared tools VISIBLE when progressive tool disclosure is on.

    A skill loaded MID-TURN (model_driven selection via load_skill, or inspect_skill) hands the
    model a procedure that names tools by hand. If disclosure narrowed the advertised set before
    that skill was chosen, those names would be missing from the schema block — a procedure
    pointing at tools the model cannot see. Revealing them closes that gap. Duck-typed and
    defensive: no disclosure view (the default — disclosure off), or any failure, is a silent
    no-op. Returns the names actually revealed."""
    names = list(getattr(skill, "tools", None) or ())
    if not names or disclosure is None or not hasattr(disclosure, "reveal"):
        return []
    try:
        return disclosure.reveal(names)
    except Exception:
        log.debug("reveal_skill_tools failed for %r", getattr(skill, "name", "?"), exc_info=True)
        return []


@dataclass
class Skill:
    name: str
    description: str
    tools: list[str]
    procedure: str
    path: str = ""
    triggers: list[str] = field(default_factory=list)  # phrases that should activate it
    steps: list = field(default_factory=list)          # optional structured steps -> deterministic run


@dataclass
class SkillContext:
    """What a selector contributes to a single run. Same type for both selectors."""
    system_additions: str = ""
    extra_tools: list[Tool] = field(default_factory=list)
    active_skill: Optional[str] = None


# Matches a top-level (unindented) `key: value` frontmatter line. Indented lines
# (multi-line YAML list items, nested block content) are left untouched so YAML's
# own block-scalar rules apply to them.
_TOPLEVEL_KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):(.*)$")


def _yaml_safe_line(line: str) -> str:
    """Defensively quote a bare `key: value` line's value before handing the block to
    yaml.safe_load.

    The existing library skills (authored against the old hand-rolled splitter, which
    just took everything after the first ':') are NOT valid YAML as-is: a plain
    (unquoted) YAML scalar can't itself contain ": " (colon-space), e.g.
    `description: ... for each channel: how concise ...` in report_builder.md. Rather
    than requiring every skill file to be quoted, JSON-quote (a valid subset of YAML
    double-quoted scalars) any top-level scalar value that isn't already a flow
    collection (`[...]`/`{...}`) or already quoted, so it round-trips as a single
    string regardless of embedded colons.
    """
    m = _TOPLEVEL_KEY_RE.match(line)
    if not m:
        return line
    key, rest = m.group(1), m.group(2)
    val = rest.strip()
    if not val:
        return line  # value continues on following (indented) lines
    if val[0] in "[{":
        return line  # flow list/map — let yaml parse it natively
    if val[0] in "'\"" and len(val) >= 2 and val[-1] == val[0]:
        return line  # already quoted
    if val[0] in "|>":
        return line  # block scalar indicator — value is on following indented lines
    return f"{key}: {json.dumps(val, ensure_ascii=False)}"


def _coerce_str_list(val) -> list:
    """Coerce a YAML-parsed `tools`/`triggers` value to list[str].

    Accepts a real YAML list, a single scalar, or a comma-separated string (back-compat
    for the inline forms `tools: [a, b]` and `tools: a, b`).
    """
    if val is None:
        return []
    if isinstance(val, list):
        return [str(v).strip() for v in val if str(v).strip()]
    if isinstance(val, str):
        if "," in val:
            return [t.strip() for t in val.split(",") if t.strip()]
        return [val.strip()] if val.strip() else []
    return [str(val)]


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """`---`-delimited frontmatter parser backed by yaml.safe_load.

    Supports scalar `key: value`, flow lists (`tools: [a, b]`), comma-separated
    scalars (`tools: a, b`), and real multi-line YAML lists. Returns (meta, body).
    Raises ValueError if frontmatter is absent/malformed.
    """
    if not text.startswith("---"):
        raise ValueError("missing frontmatter (must start with '---')")
    lines = text.splitlines()
    if lines[0].strip() != "---":
        raise ValueError("frontmatter must open with a line containing only '---'")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise ValueError("frontmatter not closed with '---'")
    block = "\n".join(_yaml_safe_line(line) for line in lines[1:end])
    try:
        meta = yaml.safe_load(block)
    except yaml.YAMLError as e:
        raise ValueError(f"invalid frontmatter YAML: {e}") from e
    if meta is None:
        meta = {}
    if not isinstance(meta, dict):
        raise ValueError("frontmatter must parse to a YAML mapping")
    if "tools" in meta:
        meta["tools"] = _coerce_str_list(meta["tools"])
    if "triggers" in meta:
        meta["triggers"] = _coerce_str_list(meta["triggers"])
    body = "\n".join(lines[end + 1:]).strip()
    return meta, body


class SkillRegistry:
    def __init__(self):
        self._skills: dict[str, Skill] = {}

    def load_dir(self, path: str) -> None:
        if not os.path.isdir(path):
            log.warning("skills dir not found: %s", path)
            return
        for fname in sorted(os.listdir(path)):
            if not fname.endswith(".md"):
                continue
            fpath = os.path.join(path, fname)
            try:
                meta, body = parse_frontmatter(open(fpath, encoding="utf-8").read())
                name = meta.get("name") or os.path.splitext(fname)[0]
                skill = Skill(
                    name=name,
                    description=meta.get("description", ""),
                    tools=meta.get("tools", []),
                    procedure=body,
                    path=fpath,
                    triggers=meta.get("triggers", []),
                    steps=_extract_steps(body, name),
                )
                if not skill.description or not skill.procedure:
                    raise ValueError("skill needs a description and a procedure body")
                self._skills[name] = skill
            except Exception as e:  # skip malformed skill, don't crash startup
                log.warning("skipping malformed skill %s: %s", fpath, e)

    def register(self, skill: Skill) -> None:
        self._skills[skill.name] = skill

    def unregister(self, name: str) -> bool:
        return self._skills.pop(name, None) is not None

    def list(self) -> list[Skill]:
        return list(self._skills.values())

    def get(self, name: str) -> Optional[Skill]:
        return self._skills.get(name)


class SkillSelector(ABC):
    name: str

    def __init__(self, registry: SkillRegistry):
        self.registry = registry

    @abstractmethod
    def prepare(self, session_id: str, user_text: str,
                requested_skill: Optional[str]) -> SkillContext:
        ...


def get_selector(name: str, registry: SkillRegistry) -> SkillSelector:
    from engine.skills.selection.explicit import ExplicitSelector
    from engine.skills.selection.model_driven import ModelDrivenSelector
    from engine.skills.selection.hybrid import HybridSelector
    if name == "explicit":
        return ExplicitSelector(registry)
    if name == "model_driven":
        return ModelDrivenSelector(registry)
    if name == "hybrid":
        return HybridSelector(registry)
    raise ValueError(f"unknown skill_selection_mode: {name!r} "
                     "(expected 'explicit', 'model_driven', or 'hybrid')")
