"""Skills — shippable procedural knowledge that sits on top of tools.

Layering (respected strictly): loop at the bottom, tools above it, skills
orchestrating tools. A skill NEVER replaces the tool system — it declares which
tools it expects and provides the procedure that uses them.

Forward-compat Property 2: a skill is LOADED DATA with a stable schema (markdown
+ frontmatter), never hardcoded in Python — so a skill could later be
rewritten/regenerated by editing the file.

The skill-selection strategy is itself under test (SKILL_SELECTION_MODE). Both
selectors return the SAME SkillContext, so the loop consumes them identically and
never branches on selection mode.
"""
from __future__ import annotations

import json
import logging
import os
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional

from engine.tools.base import Tool

log = logging.getLogger("argus.skills")

# A skill may embed a ```steps fenced JSON block of structured TOOL/MODEL steps (same shape as a
# routine). When present, the skill runs DETERMINISTICALLY through the routine executor — the
# harness dispatches the tool steps itself and only calls the model for model steps — instead of
# injecting prose for the model to follow. The prose body still serves as documentation/fallback.
_STEPS_RE = re.compile(r"```steps\s*\n(.*?)\n```", re.DOTALL)


def _extract_steps(body: str, name: str) -> list:
    """Pull and shape-validate a skill's optional ```steps block. Returns [] (prose-only skill) if
    absent, not valid JSON, not a list, or not a valid step sequence — a bad block never breaks the
    skill, it just falls back to model-driven prose."""
    m = _STEPS_RE.search(body or "")
    if not m:
        return []
    try:
        data = json.loads(m.group(1))
    except Exception as e:
        log.warning("skill %s: ```steps block is not valid JSON, ignoring it: %s", name, e)
        return []
    if not isinstance(data, list):
        log.warning("skill %s: ```steps must be a JSON array, ignoring it", name)
        return []
    try:
        from engine.routines.store import Routine, validate_routine
        r = Routine(name="skill_steps", steps=data)
        validate_routine(r)          # shape-only (no tool existence check); fills default step ids
        return r.steps
    except Exception as e:
        log.warning("skill %s: invalid ```steps, ignoring them: %s", name, e)
        return []


@dataclass
class Skill:
    name: str
    description: str
    tools: list[str]
    procedure: str
    path: str = ""
    triggers: list[str] = field(default_factory=list)  # phrases that should activate it
    steps: list = field(default_factory=list)          # optional structured steps -> deterministic run


@dataclass
class SkillContext:
    """What a selector contributes to a single run. Same type for both selectors."""
    system_additions: str = ""
    extra_tools: list[Tool] = field(default_factory=list)
    active_skill: Optional[str] = None


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Minimal `---`-delimited frontmatter parser (no yaml dependency).

    Supports scalar `key: value` and list `tools: [a, b]` or `tools: a, b`.
    Returns (meta, body). Raises ValueError if frontmatter is absent/malformed.
    """
    if not text.startswith("---"):
        raise ValueError("missing frontmatter (must start with '---')")
    lines = text.splitlines()
    if lines[0].strip() != "---":
        raise ValueError("frontmatter must open with a line containing only '---'")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise ValueError("frontmatter not closed with '---'")
    meta: dict = {}
    for line in lines[1:end]:
        if not line.strip() or line.strip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if key in ("tools", "triggers"):
            val = val.strip("[]")
            meta[key] = [t.strip().strip("'\"") for t in val.split(",") if t.strip()]
        else:
            meta[key] = val.strip("'\"")
    body = "\n".join(lines[end + 1:]).strip()
    return meta, body


class SkillRegistry:
    def __init__(self):
        self._skills: dict[str, Skill] = {}

    def load_dir(self, path: str) -> None:
        if not os.path.isdir(path):
            log.warning("skills dir not found: %s", path)
            return
        for fname in sorted(os.listdir(path)):
            if not fname.endswith(".md"):
                continue
            fpath = os.path.join(path, fname)
            try:
                meta, body = parse_frontmatter(open(fpath, encoding="utf-8").read())
                name = meta.get("name") or os.path.splitext(fname)[0]
                skill = Skill(
                    name=name,
                    description=meta.get("description", ""),
                    tools=meta.get("tools", []),
                    procedure=body,
                    path=fpath,
                    triggers=meta.get("triggers", []),
                    steps=_extract_steps(body, name),
                )
                if not skill.description or not skill.procedure:
                    raise ValueError("skill needs a description and a procedure body")
                self._skills[name] = skill
            except Exception as e:  # skip malformed skill, don't crash startup
                log.warning("skipping malformed skill %s: %s", fpath, e)

    def register(self, skill: Skill) -> None:
        self._skills[skill.name] = skill

    def unregister(self, name: str) -> bool:
        return self._skills.pop(name, None) is not None

    def list(self) -> list[Skill]:
        return list(self._skills.values())

    def get(self, name: str) -> Optional[Skill]:
        return self._skills.get(name)


class SkillSelector(ABC):
    name: str

    def __init__(self, registry: SkillRegistry):
        self.registry = registry

    @abstractmethod
    def prepare(self, session_id: str, user_text: str,
                requested_skill: Optional[str]) -> SkillContext:
        ...


def get_selector(name: str, registry: SkillRegistry) -> SkillSelector:
    from engine.skills.selection.explicit import ExplicitSelector
    from engine.skills.selection.model_driven import ModelDrivenSelector
    from engine.skills.selection.hybrid import HybridSelector
    if name == "explicit":
        return ExplicitSelector(registry)
    if name == "model_driven":
        return ModelDrivenSelector(registry)
    if name == "hybrid":
        return HybridSelector(registry)
    raise ValueError(f"unknown skill_selection_mode: {name!r} "
                     "(expected 'explicit', 'model_driven', or 'hybrid')")
